Все задачи 02-components
js-tasks-ru/vue-20211116_andrey0995 pull request #3
Opened 2021-12-04 08:21 UTC by glukhovandrey

2021-12-04 08:22 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2021-12-04 14:25 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2021-12-04 17:28 UTC, ShGKme requested changes
Требуется небольшая правка в 3-sfc/01-VBindCover

2021-12-04 17:28 UTC, ShGKme commented on 02-components/04-MeetupInfo/MeetupInfo.js
> +    },
Атрибут datetime ожидает дату по UTC, а getX возвращают в локальной TZ. Требуется использовать `getUTCX` методы. А проще сразу взять нужную часть от `toISOString()`, как мы делали на вебинаре: https://github.com/js-tasks-ru/vue3-course-materials/blob/master/02-components/02-page-meetups/components/MeetupsListItem.js#L20-L51

2021-12-04 17:28 UTC, ShGKme commented on 03-sfc/01-VBindCover/components/MeetupCover.vue
>  };
Пустая строка - не очень корректная ссылка. В итоге при отсутствии изображения в стили добавляется фон с `url('')`. Требуется проверять, есть ли `image`, и возвращать `var(--default-cover);` при отсутствии.

2021-12-06 09:40 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2021-12-06 09:41 UTC, glukhovandrey commented
Спасибо. По замечаниям вес исправления.

2021-12-07 11:32 UTC, ShGKme approved these changes
Принято 👍

2021-12-07 11:33 UTC, merged